log_level: INFO
hcu_controller:
  enabled: true
  serial_device: /dev/ttyUSB0                                                       # Path to the serial device file attached to the HCU serial connection
  serial_baud_rate: 115200
  shutdown_delay_s: 180                                                             # Delay after having received SHUTDOWN command to executing shutdown (in seconds)
  shutdown_command: ['sudo', 'shutdown', '-h', 'now']                               # Don't accidentally shut down your computer and use a dummy command like "touch /tmp/shutdown_called" for testing
uplink_monitor:
  enabled: true
  wwan_interface: 'wwan0'                                                           # WWAN interface name (see mmcli -m any and check System.ports, it's probably wwan0)
  wwan_apn: 'test.apn'                                                              # APN to use for the WWAN connection
  check_interval_s: 10                                                              # How often to trigger the connection check
  ping:                                                                             # ping configuration (see config.py for more options)
    target: '1.1.1.1'                                                               # Target to ping for connection checks
  modem:
    type: 'dummy'                                                                   # Choose the modem implementation (dummy does nothing)
  # modem:
    # type: 'tcl_ike41ve1'
    # reboot_enabled: false                                                         # Enable rebooting the machine as a last resort measure if the modem repeatedly cannot be detected
    # reboot_threshold_s: 300                                                       # How long after first failed connection until reboot is triggered
gps:
  enabled: true
  init_cmd: ['true']                                                                # Optional command to initialize GPS, e.g. set measurement rate ['ubxtool', '-p', 'CFG-RATE,200']
  gpsd_host: localhost
  gpsd_port: 2947
    
frontend:
  enabled: true
  path: dist